### ISSUE TITLE
/usr/lib/x86_64-linux-gnu/glusterfs/mount-shared-storage.sh: No such file or directory

### ISSUE THREAD

**Issue by richard-scott** [gluster/glusterfs-debian#10]
I've just installed the latest 3.12.0-2 on stretch and I get this error:

```
Sep 06 09:56:29 localhost systemd[3646]: glusterfssharedstorage.service: Failed at step EXEC spawning /usr/lib/x86_64-linux-gnu/glusterfs/mount-shared-storage.sh: No such file or directory
Sep 06 09:56:29 localhost systemd[1]: glusterfssharedstorage.service: Control process exited, code=exited status=203
```

I can't find that file anywhere.

**Comment by kalebskeithley** [comment]
fixed in 3.12.0-3, jessie, stretch, buster
and ubuntu on launchpad

**Comment by danelsan** [comment]
I migrate to 3.13.2 but give me always same error

systemd[1]: glusterfssharedstorage.service: Failed with result 'exit-code'

**Comment by kalebskeithley** [comment]
Please file a BZ for gluster at https://bugzilla.redhat.com/enter_bug.cgi?product=GlusterFS
