### ISSUE TITLE
glusterfs-common v 3.7.8 for stretch is not installable on stretch

### ISSUE THREAD

**Issue by renepavlik** [gluster/glusterfs-debian#11]
It depends on unavailable package `libreadline6 (>= 6.0) (UNAVAILABLE)`. In stretch, there is only `libreadline7`.

**Comment by kalebskeithley** [comment]
There were twelve updates after 3.7.8, perhaps it was fixed in one of those. That aside, 3.7 reached EOL around January 2017.
