### ISSUE TITLE
Redundant logrotate configuration in glusterfs-common 3.10.6 for Ubuntu 16.04

### ISSUE THREAD

**Issue by a-evseev** [gluster/glusterfs-debian#12]
glusterfs-common contains two logrotate configurations:

- /etc/logrotate.d/glusterfs defines weekly logs rotation and contains correct postrotate scripts
- /etc/logrotate.d/glusterfs-common defines daily rotation and does not send HUP to glusterfsd processes

**Comment by kalebskeithley** [comment]
glusterfs-common_3.10.6 (or any version) from the PPA does not contain (has never contained, AFAICT) an /etc/logrotate.d/glusterfs-common file. E.g.
% dpkg-deb -c glusterfs-common_3.10.6-ubuntu1~xenial1_amd64.deb | grep etc
drwxr-xr-x root/root         0 2017-10-03 10:14 ./etc/
drwxr-xr-x root/root         0 2017-10-03 10:14 ./etc/logrotate.d/
-rw-r--r-- root/root      1001 2017-10-03 09:42 ./etc/logrotate.d/glusterfs-georep
-rw-r--r-- root/root       626 2017-10-03 09:42 ./etc/logrotate.d/glusterfs
...

It looks like that file is left over from installing the 3.7.6 packages from xenial base. See [](https://packages.ubuntu.com/xenial/amd64/glusterfs-common/filelist)

**Comment by kalebskeithley** [comment]
It looks like that file is left over from installing the 3.7.6 packages from xenial base. See  [glusterfs-common contents(https://packages.ubuntu.com/xenial/amd64/glusterfs-common/filelist)
