### ISSUE TITLE
virt group option file missing in Ubuntu Xenial deb packages

### ISSUE THREAD

**Issue by wkbneit** [gluster/glusterfs-debian#15]
ppa:gluster/glusterfs-3.12 for U16 LTS (Xenial) Maybe other versions.

install was missing the virt group file (or any group) in /var/lib/glusterd/groups

the "virt" group settings are really important when running a VM host as they include sharding among other enhancements

**Comment by kalebskeithley** [comment]
fixed in 3.10.6-ubuntu1-{trusty,xenial,zesty,artful}2 and 3.12.2-ubuntu1-{xenial,zesty,artful}2 .debs
