### ISSUE TITLE
xenial-glusterfs-common 3.12.2 logrotate issues

### ISSUE THREAD

**Issue by jerzyk** [gluster/glusterfs-debian#16]
cron reports an error:

```
/etc/cron.daily/logrotate:
error: glusterfs-common:1 duplicate log entry for /var/log/glusterfs/cli.log
```

**Comment by kalebskeithley** [comment]
/etc/logrotate.d/glusterfs-common is left over from previous versions. Just delete it.

If you can suggest changes to the packaging bits to ensure it is deleted by an update it that would be very helpful.
