### ISSUE TITLE
bad url key in process for add depots

### ISSUE THREAD

**Issue by codati** [gluster/glusterfs-debian#17]
hi,
in https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/
url : http://download.gluster.org/pub/gluster/glusterfs/3.13/rsa.pub
get 404
good url:
https://download.gluster.org/pub/gluster/glusterfs/3.13/pub.rsa

**Comment by kalebskeithley** [comment]
fixed

**Comment by codati** [comment]
not fix:
is not http/https
bug is rsa.pub => pub.rsa

**Comment by codati** [comment]
is fixed thx
