### ISSUE TITLE
Development Dependencies in Common Package.

### ISSUE THREAD

**Issue by suwalski** [gluster/glusterfs-debian#2]
The glusterfs-common package seems to have hardcoded dependencies on -dev packages:

```
Package: glusterfs-common
Section: libs
Architecture: any
Pre-Depends: ${misc:Pre-Depends},
 dpkg (>= 1.15.6~)
Depends: ${misc:Depends},
 ${shlibs:Depends},
 attr,
 uuid-dev,
 libacl1-dev,
```

It is very unusual to runtime-depend on -dev packages. I believe it is in error.

**Comment by suwalski** [comment]
I see the packaging was altered. Looks like "libacl1-dev" is in the Build-Depends list twice, and "libacl1" likely does not need to the in the "Depends" line, because libraries get populated automatically. In fact, the comment suggests that libacl1-dev was only added for a pkgconfig file that isn't useful at runtime.

**Comment by suwalski** [comment]
In fact, the build automatically put in `libossp-uuid16` as the dependency, so depending on the command-line tools `uuid` package is not helpful.

**Comment by suwalski** [comment]
Created pull request #3 to deal with this.

**Comment by kalebskeithley** [comment]
PR#3 was merged in April 2016, closing
