### ISSUE TITLE
Geo-Replication is broken in Ubuntu PPA after libc-Update

### ISSUE THREAD

**Issue by timmmmmey** [gluster/glusterfs-debian#20]
Hi,

glusterfs  geo-replication isn't woking anymore after updating to libc6:amd64 2.23-0ubuntu10
For more details see  [https://www.spinics.net/lists/gluster-users/msg33617.html](https://www.spinics.net/lists/gluster-users/msg33617.html) .

Downgrading to libc6:amd64 2.23-0ubuntu3 resolves the issue, but this is no long-time solution.

Best regards,

**Comment by kalebskeithley** [comment]
This is a bug in gluster, not in the debian packaging of gluster, right?

**Comment by kalebskeithley** [comment]
Please open a BZ for gluster at https://bugzilla.redhat.com/enter_bug.cgi?product=GlusterFS
