### ISSUE TITLE
duplicate logrotate config after upgrading packages

### ISSUE THREAD

**Issue by bwerthmann** [gluster/glusterfs-debian#21]
commit 55786a5c0dd56244eeffad45adfcd686f8c0e96d (`3.10.3-ubuntu1~trusty2`) introduces `/etc/logrotate.d/glusterfs` and `/etc/logrotate.d/glusterfs-georep` from Gluster's "extras".

Prior package versions contain logrotate files `glusterfs-common` and/or `glusterfs-server` from the debian directory.

After the upgrade, log rotate complains about two definitions for the same file:
```
error: glusterfs-common:1 duplicate log entry for /var/log/glusterfs/*.log
```

The change in the config is major: 7 days to 52 weeks.

Expectation: User should be prompted what to do with config files during the package upgrade. 

https://www.debian.org/doc/debian-policy/#document-ap-pkg-conffiles

if "keep existing config files" is selected during package upgrade, "new" logrotate config have a `dpkg-dist` extension. Logrotate ignores extension `dpkg-dist` when included because it is a "tabooext", others are:

```
At startup, the taboo extension list contains  .rpmsave,  .rpmorig,  ~,  .disabled,  .dpkg-old,  .dpkg-dist,
              .dpkg-new, .cfsaved, .ucf-old, .ucf-dist, .ucf-new, .rpmnew, .swp, .cfsaved, .rhn-cfg-tmp-*
```

**Comment by kalebskeithley** [comment]
yeah, a year after the fact... All packages since, and going forward don't have an issue. I suggest manually removing the old files and move on.
Not going to do anything to try to fix this.
