### ISSUE TITLE
Package install fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by JohnKiller** [gluster/glusterfs-debian#22]
Hi, running `apt install glusterfs-server -y` on a freshly installed Ubuntu 18.04 machine results in this output:

	Setting up glusterfs-server (3.13.2-1build1) ...
	Job for glustereventsd.service failed because a timeout was exceeded.
	See "systemctl status glustereventsd.service" and "journalctl -xe" for details.
	invoke-rc.d: initscript glustereventsd, action "start" failed.
	● glustereventsd.service - LSB: Gluster Events Server
	   Loaded: loaded (/etc/init.d/glustereventsd; generated)
	   Active: failed (Result: timeout) since Wed 2018-05-02 21:05:37 UTC; 8ms ago
		 Docs: man:systemd-sysv-generator(8)
	  Process: 6769 ExecStart=/etc/init.d/glustereventsd start (code=killed, signal=TERM)
		Tasks: 3 (limit: 4704)
	   CGroup: /system.slice/glustereventsd.service
			   ├─6782 /usr/bin/python /usr/sbin/glustereventsd -p /var/run/glustereventsd.pid
			   └─6786 /usr/bin/python /usr/sbin/glustereventsd -p /var/run/glustereventsd.pid
	dpkg: error processing package glusterfs-server (--configure):
	 installed glusterfs-server package post-installation script subprocess returned error exit status 1

Running again the same apt command says that Gluster is already installed (and in fact gluster works as expected), however this breaks automated installations.

Tell me if you need any other logs (`journalctl -xe` is empty). Thanks

**Comment by kalebskeithley** [comment]
Installing the 4.0.2 on Bionic worked for me. 3.13 is EOL.

If glustereventsd failed to start that's a bug with glustereventsd and does not, AFAICT, have anything to do with packaging. If you believe there is a problem with glustereventsd then please file a bugzilla at https://bugzilla.redhat.com/enter_bug.cgi?product=GlusterFS

**Comment by JohnKiller** [comment]
Thanks for your response. Just for clarification, what version of glusterfs is shipped with bionic, without using any ppa? Because I did tests with a digital ocean VM, and without messing with apt it installed 3.13

**Comment by JohnKiller** [comment]
https://packages.ubuntu.com/bionic/glusterfs-server

I believe this is the package I got. It says 3.13. Did bionic ship a EOL version?

**Comment by kalebskeithley** [comment]
Yes, I get 3.13 on bionic when I don't use the PPA.

3.13 may not have been EOL when Ubuntu added it to bionic.  3.13. was well advertised as a STM (short term maintenance) release. I hope they update to 4.0. I wish who ever it is in Ubuntu would work more closely with us.
That's one of the reasons we suggest using the PPA.

**Comment by jacobuserasmus** [comment]
I have the same problem. Glusterfs-server install on a fresh machine failed 2/3 times so far. Ubuntu 18.04

**Comment by ThinkZ** [comment]
I try it with same problem...

Oct 12 18:48:05 u18s01 systemd[1]: Starting LSB: Gluster Events Server...
Oct 12 18:48:05 u18s01 glustereventsd[3226]:  * Starting glustereventsd service glustereventsd
Oct 12 18:53:06 u18s01 systemd[1]: glustereventsd.service: Start operation timed out. Terminating.
Oct 12 18:53:06 u18s01 systemd[1]: glustereventsd.service: Failed with result 'timeout'.
Oct 12 18:53:06 u18s01 systemd[1]: Failed to start LSB: Gluster Events Server.

same error message on ubuntu source and ppa:gluster/glusterfs-4.1

**Comment by willkara** [comment]
Installing on 18.04 still fails by virtue of it trying to install 3.13

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

I had to install the PPA manually for it to work and install:

Setting up glusterfs-common (4.1.7-ubuntu1~bionic1) ...
Setting up glusterfs-client (4.1.7-ubuntu1~bionic1) ...
Setting up glusterfs-server (4.1.7-ubuntu1~bionic1) ...

**Comment by aroute** [comment]
I'm running into the same exact problem here. Tried 4.1 as last comment suggested. I can install, but I get this on probing:
peer probe: failed: Probe returned with Transport endpoint is not connected

Fresh Ubuntu 18.04.2 LTS

**Comment by kalebskeithley** [comment]
I installed 5.3 from the PPA on my bionic box and a simple single brick
volume works fine.

You can get help on IRC on freenode/#gluster or on the gluster-users
mailing list at  gluster-users@gluster.org
