### ISSUE TITLE
glusterd.service is missing with 4.1.0

### ISSUE THREAD

**Issue by kaba1ah** [gluster/glusterfs-debian#24]
glusterd.service seems to be missing while installing 4.1.0 from https://download.gluster.org/pub/gluster/glusterfs/4.1/LATEST/ under Debian Stretch.

Thanks.

**Comment by kalebskeithley** [comment]
fixed in 4.1.0-2 packages for stretch and buster on download.gluster.org
fixed in 4.1.0-3 packages for xenial, atomic, bionic, cosmic on Launchpad PPA
