### ISSUE TITLE
Storhaug dependencies do not install on Debian

### ISSUE THREAD

**Issue by ryno83** [gluster/glusterfs-debian#27]
The dependencies e.g. ctdb, nfs-ganesha-gluster, glusterfs are not automatically install on Debian.

**Comment by epol** [comment]
To add some context, this issue comes from the gluster/storhaug project, so it is talking about to the `storhaug` package.

**Comment by ryno83** [comment]
@kalebskeithley Is it the right place for packaging issues with Storhaug ?

**Comment by kalebskeithley** [comment]
for storhaug, yes, here is fine.  But the ganesha gfapi.logrotate is not gluster or storhaug, it's ganesha. Post issues  in https://github.com/nfs-ganesha/nfs-ganesha-debian/issues

**Comment by r4nd0m123** [comment]
The same thing is occurring for Ubuntu Bionic as well.

**Comment by kalebskeithley** [comment]
storhaug is dead

**Comment by ryno83** [comment]
Thats it... no replacement solution ?
