### ISSUE TITLE
gluster client v4.1.5 package for s390x

### ISSUE THREAD

**Issue by AnitaNayak** [gluster/glusterfs-debian#30]
On s390x, gluster client v4.1.5 is not available. It is available for other ARCHs. Could it be possible to get gluster client v4.1.5 on s390x community one.
We raised one issue regarding procedures to build .deb package for gluster-client v4.1.5. It may take some time for us to build it and verify. If it could be available from community it would be good.

Thank you.

**Comment by kalebskeithley** [comment]
s390x was added/enabled a while ago. There are glusterfs-4.1.x packages for s390x for all the active versions of Ubuntu. Thus closing this.
