### ISSUE TITLE
Packages should provide libglusterfs0 instead of conflicting

### ISSUE THREAD

**Issue by nepeat** [gluster/glusterfs-debian#32]
I propose that glusterfs-common should provide libglusterfs0 instead of conflicting with it because of this conflict pointed out in a Proxmox bug ticket. From what I understand in the ticket, Debian’s libglusterfs0 is conflicting with glusterfs-common instead of being provided by it.

https://bugzilla.proxmox.com/show_bug.cgi?id=2269

**Comment by Fabian-Gruenbichler** [comment]
the current situation in Debian Buster is that no packages from the gluster community repositories can be installed unless every stock Debian package that depends on gluster is removed, effectively making the community repos unusable for Debian Buster and later.

please either follow the downstream/distro packaging changes (split out shared libraries into their own packages, instead of shipping them via glusterfs-common) or at least set your package metadata accordingly to stay compatible (e.g., provides/replaces with appropriate versions and package names).

**Comment by kalebskeithley** [comment]
> the current situation in Debian Buster is that no packages from the gluster community repositories can be installed unless every stock Debian package that depends on gluster is removed, effectively making the community repos unusable for Debian Buster and later.
> 
> please either follow the downstream/distro packaging changes (split out shared libraries into their own packages, instead of shipping them via glusterfs-common) or at least set your package metadata accordingly to stay compatible (e.g., provides/replaces with appropriate versions and package names).

Are you going to send a PR?

**Comment by nepeat** [comment]
> Are you going to send a PR?

Sounds like a good plan but how would I approach each of the branches for Debian? I see there are about 12 branches for Buster and presumably the same for Stretch. Is there a way to update most of them from a single master branch or are all of them edited by hand for each update to upstream?

**Comment by kalebskeithley** [comment]
> > Are you going to send a PR?
> 
> Sounds like a good plan but how would I approach each of the branches for Debian? I see there are about 12 branches for Buster and presumably the same for Stretch. Is there a way to update most of them from a single master branch or are all of them edited by hand for each update to upstream?

There isn't.  (Blame semiosis ?!?) 

I would suggest only fixing buster-glusterfs-5 and buster-glusterfs-6 branches at this point  GlusterFS-7 is coming soon, FYI.  And glusterfs-4.1 will EOL when -7 is released, so I don't think it's worth bothering with the buster-glusterfs-41branch.

Fabian says it's only buster that's "broken" so I wouldn't bother with changing stretch. At least not until someone says it's an issue.

**Comment by kalebskeithley** [comment]
Packages for the just released glusterfs-5.9 and glusterfs-6.5 for buster, bullseye, disco, and eoan are all built with new packaging files derived from the latest Debian and Ubuntu packaging files for glusterfs-5 and glusterfs-6. These should now be compatible and interchangeable with the glusterfs packages in the distribution base repos.

buster and bullseye packages are on https://download.gluster.org now. disco and eoan packages are in the Gluster PPA on launchpad now.
