### ISSUE TITLE
Possible to break installs due to incompatible gluster lib versions

### ISSUE THREAD

**Issue by srstsavage** [gluster/glusterfs-debian#34]
Testing with Debian 10, it's currently possible to install incompatible versions of glusterfs-common and its gluster lib dependencies (e.g. libglusterfs0). This appears to be because there is no version specified in the Debian package dependency. 

Example, starting with a working Deb 10 host with Gluster 6.5, upgrading only glusterfs-client (resulting in a broken install with glusterfs-client/common 7.0 and libglusterfs0 6.5), and a working system after upgrading all packages.

```
#gluster works
$ cat /etc/debian_version 
10.1
$ grep ^deb /etc/apt/sources.list.d/gluster.list 
deb https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/buster/amd64/apt buster main
$ /sbin/glusterfs --version  | head -n 1
glusterfs 6.5
$ sudo apt install -y glusterfs-client > /dev/null
#gluster is broken
$ /sbin/glusterfs --version  | head -n 1
/sbin/glusterfs: symbol lookup error: /sbin/glusterfs: undefined symbol: glusterfs_graph_fini
$ dpkg -s glusterfs-client | grep Version
Version: 7.0-1
$ dpkg -s glusterfs-common | grep Version
Version: 7.0-1
$ dpkg -s glusterfs-common | grep Depends
Depends: libacl1 (>= 2.2.23), libaio1 (>= 0.3.93), libc6 (>= 2.28), libgfapi0, libgfchangelog0, libgfrpc0, libgfxdr0, libglusterfs0, libibverbs1 (>= 1.1.6), libncurses6 (>= 6), librdmacm1 (>= 1.0.19), libreadline7 (>= 6.0), libssl1.1 (>= 1.1.0), libtinfo6 (>= 6), libtirpc3 (>= 1.1.4), liburcu6 (>= 0.10.0), libuuid1 (>= 2.16), libxml2 (>= 2.7.4), zlib1g (>= 1:1.1.4), python3:any, python3-prettytable, python3-requests, python3-jwt, attr, xfsprogs, e2fsprogs, psmisc
$ dpkg -s libglusterfs0 | grep Version
Version: 6.5-1
$ sudo apt upgrade -y > /dev/null
# libgfapi0 libgfchangelog0 libgfrpc0 libgfxdr0 libglusterfs0 are upgraded...
#gluster works again
$ dpkg -s libglusterfs0 | grep Version
Version: 7.0-1
$ /sbin/glusterfs --version  | head -n 1
glusterfs 7.0

```

[Looking at the package repo](https://download.gluster.org/pub/gluster/glusterfs/7/7.0/Debian/buster/amd64/apt/dists/buster/main/binary-amd64/Packages
), it looks like glusterfs-common depends on various Gluster libs but not to any particular version of them:

> Depends: libacl1 (>= 2.2.23), libaio1 (>= 0.3.93), libc6 (>= 2.28), libgfapi0, libgfchangelog0, libgfrpc0, libgfxdr0, libglusterfs0, libibverbs1 (>= 1.1.6), libncurses6 (>= 6), librdmacm1 (>= 1.0.19), libreadline7 (>= 6.0), libssl1.1 (>= 1.1.0), libtinfo6 (>= 6), libtirpc3 (>= 1.1.4), liburcu6 (>= 0.10.0), libuuid1 (>= 2.16), libxml2 (>= 2.7.4), zlib1g (>= 1:1.1.4), python3:any, python3-prettytable, python3-requests, python3-jwt, attr, xfsprogs, e2fsprogs, psmisc
Breaks: glusterfs-server (<< 3.4.0~qa5)

So, it's possible install glusterfs-common, glusterfs-client, etc with incompatible versions of the lib packages (libglusterfs0 etc).

I _think_ this solution is to add the `-VUpstream-Version` (or just `-V` if you're using an older version) to `dh_makeshlibs` [here](https://github.com/gluster/glusterfs-debian/blob/buster-glusterfs-7/debian/rules#L55) in order to get a version specified with the lib dependencies, but I'm not certain (I haven't been able to get package builds working locally). See `man dh_makeshlibs`.

**Comment by kalebskeithley** [comment]
The packaging bits are copied verbatim (or nearly so) from Patrick Matthäi's Debian
packaging bits. The official Debian dist packages must have the same
problem. I just checked and there don't seem to have been any changes that
would address this.

Not being a Debian packaging expert I can't say whether using
-VUpstream-Version is correct, or whether it would adversely affect the
non-glusterfs dependencies, e.g. libibverbs, where a specific version isn't
specified. I suppose I could do a build with it and see what happens.

Otherwise, in a vacuum I'd probably err on the side of caution (and
simplicity?) and add explicit Depends: to glusterfs-common for the
specific/explicit version of libglusterfs0, libgfapi0, libchangelog0,
libgfrpc0, and libgfxdr0,

**Comment by kalebskeithley** [comment]
Am 06.11.2019 um 14:31 schrieb Kaleb Keithley:
>
> The packaging bits are copied verbatim (or nearly so) from Patrick's
> Debian packaging bits. The official Debian dist packages must have the
> same problem. I just checked and there don't seem to have been any
> changes that would address this. 
>
> Not being a Debian packaging expert I can't say whether using
> -VUpstream-Version is correct, or whether it would adversely affect
> the non-glusterfs dependencies, e.g. libibverbs, where a specific
> version isn't specified. I suppose I could do a build with it and see
> what happens.
>
> Otherwise, in a vacuum I'd probably err on the side of caution (and
> simplicity?) and add explicit Depends: to glusterfs-common for the
> specific/explicit version of libglusterfs0, libgfapi0, libchangelog0,
> libgfrpc0, and libgfxdr0,

If this is the case, then upstream missed SONAME bumps for the libraries
which implies, that they are not compatible



-- 
/*
Mit freundlichem Gruß / With kind regards,
 Patrick Matthäi
 GNU/Linux Debian Developer

  Blog: http://www.linux-dev.org/
E-Mail: pmatthaei@debian.org
        patrick@linux-dev.org
*/

**Comment by kalebskeithley** [comment]
On Wed, Nov 6, 2019 at 8:50 AM Patrick Matthäi <pmatthaei@debian.org> wrote:

> Am 06.11.2019 um 14:31 schrieb Kaleb Keithley:
> >
> > The packaging bits are copied verbatim (or nearly so) from Patrick's
> > Debian packaging bits. The official Debian dist packages must have the
> > same problem. I just checked and there don't seem to have been any
> > changes that would address this.
> >
> > Not being a Debian packaging expert I can't say whether using
> > -VUpstream-Version is correct, or whether it would adversely affect
> > the non-glusterfs dependencies, e.g. libibverbs, where a specific
> > version isn't specified. I suppose I could do a build with it and see
> > what happens.
> >
> > Otherwise, in a vacuum I'd probably err on the side of caution (and
> > simplicity?) and add explicit Depends: to glusterfs-common for the
> > specific/explicit version of libglusterfs0, libgfapi0, libchangelog0,
> > libgfrpc0, and libgfxdr0,
>
> If this is the case, then upstream missed SONAME bumps for the libraries
>

glusterfs (upstream, downstream, etc.) has never used SONAME for library
versioning.


> which implies, that they are not compatible
>

Indeed, and that has always been the case.

I suppose someone could make the case that it's a problem, and I personally
wouldn't disagree, but I rather doubt anything is going to change after 10+
years of this. (At least libgfapi uses versioned symbols to maintain
compatibility across versions.) But that's not a problem with the packaging
files.

Do you want to express an opinion about the use of -VUpstream-Version or
explicit Depends: in the glusterfs-common section of the rules file?

--

Kaleb

**Comment by kalebskeithley** [comment]
On Wed, Nov 6, 2019 at 9:05 AM Kaleb Keithley <kkeithle@redhat.com> wrote:

>
>>
> Do you want to express an opinion about the use of -VUpstream-Version or
> explicit Depends: in the glusterfs-common section of the rules file?
>

... in the glusterfs-common section of the control file?

--

Kaleb

**Comment by srstsavage** [comment]
FWIW it does look like `-VUpstream-Version` fixes this.

```
diff --git a/debian/rules b/debian/rules
index 47755d7..eacbe37 100755
--- a/debian/rules
+++ b/debian/rules
@@ -52,4 +52,4 @@ override_dh_python3:
        dh_python3
 
 override_dh_makeshlibs:
-       dh_makeshlibs --no-scripts
+       dh_makeshlibs --no-scripts -VUpstream-Version
```

Here's a diff of all the *.substvars files produced by the build before and after this change

```
diff substvars/glusterfs-common.substvars substvars-change/glusterfs-common.substvars
2c2
< shlibs:Depends=libacl1 (>= 2.2.23), libaio1 (>= 0.3.93), libc6 (>= 2.28), libgfapi0, libgfchangelog0, libgfrpc0, libgfxdr0, libglusterfs0, libibverbs1 (>= 1.1.6), libncurses6 (>= 6), librdmacm1 (>= 1.0.19), libreadline7 (>= 6.0), libssl1.1 (>= 1.1.0), libtinfo6 (>= 6), libtirpc3 (>= 1.1.4), liburcu6 (>= 0.10.0), libuuid1 (>= 2.16), libxml2 (>= 2.7.4), zlib1g (>= 1:1.1.4)
---
> shlibs:Depends=libacl1 (>= 2.2.23), libaio1 (>= 0.3.93), libc6 (>= 2.28), libgfapi0 (>= 7.0), libgfchangelog0 (>= 7.0), libgfrpc0 (>= 7.0), libgfxdr0 (>= 7.0), libglusterfs0 (>= 7.0), libibverbs1 (>= 1.1.6), libncurses6 (>= 6), librdmacm1 (>= 1.0.19), libreadline7 (>= 6.0), libssl1.1 (>= 1.1.0), libtinfo6 (>= 6), libtirpc3 (>= 1.1.4), liburcu6 (>= 0.10.0), libuuid1 (>= 2.16), libxml2 (>= 2.7.4), zlib1g (>= 1:1.1.4)
diff substvars/glusterfs-server.substvars substvars-change/glusterfs-server.substvars
2c2
< shlibs:Depends=libacl1 (>= 2.2.23), libc6 (>= 2.14), libgfapi0, libgfrpc0, libgfxdr0, libglusterfs0, libncurses6 (>= 6), libreadline7 (>= 6.0), libssl1.1 (>= 1.1.0), libtinfo6 (>= 6), libtirpc3 (>= 1.1.4), libuuid1 (>= 2.16), libxml2 (>= 2.7.4)
---
> shlibs:Depends=libacl1 (>= 2.2.23), libc6 (>= 2.14), libgfapi0 (>= 7.0), libgfrpc0 (>= 7.0), libgfxdr0 (>= 7.0), libglusterfs0 (>= 7.0), libncurses6 (>= 6), libreadline7 (>= 6.0), libssl1.1 (>= 1.1.0), libtinfo6 (>= 6), libtirpc3 (>= 1.1.4), libuuid1 (>= 2.16), libxml2 (>= 2.7.4)
diff substvars/libgfapi0.substvars substvars-change/libgfapi0.substvars
1c1
< shlibs:Depends=libacl1 (>= 2.2.23), libc6 (>= 2.14), libgfrpc0, libgfxdr0, libglusterfs0, libssl1.1 (>= 1.1.0), libtirpc3 (>= 1.1.4)
---
> shlibs:Depends=libacl1 (>= 2.2.23), libc6 (>= 2.14), libgfrpc0 (>= 7.0), libgfxdr0 (>= 7.0), libglusterfs0 (>= 7.0), libssl1.1 (>= 1.1.0), libtirpc3 (>= 1.1.4)
diff substvars/libgfchangelog0.substvars substvars-change/libgfchangelog0.substvars
1c1
< shlibs:Depends=libc6 (>= 2.14), libgfrpc0, libgfxdr0, libglusterfs0, libssl1.1 (>= 1.1.0), libtirpc3 (>= 1.1.4)
---
> shlibs:Depends=libc6 (>= 2.14), libgfrpc0 (>= 7.0), libgfxdr0 (>= 7.0), libglusterfs0 (>= 7.0), libssl1.1 (>= 1.1.0), libtirpc3 (>= 1.1.4)
diff substvars/libgfrpc0.substvars substvars-change/libgfrpc0.substvars
1c1
< shlibs:Depends=libc6 (>= 2.14), libgfxdr0, libglusterfs0, libssl1.1 (>= 1.1.0), libtirpc3 (>= 1.1.4)
---
> shlibs:Depends=libc6 (>= 2.14), libgfxdr0 (>= 7.0), libglusterfs0 (>= 7.0), libssl1.1 (>= 1.1.0), libtirpc3 (>= 1.1.4)
diff substvars/libgfxdr0.substvars substvars-change/libgfxdr0.substvars
1c1
< shlibs:Depends=libc6 (>= 2.4), libglusterfs0, libssl1.1 (>= 1.1.0), libtirpc3 (>= 1.1.4)
---
> shlibs:Depends=libc6 (>= 2.4), libglusterfs0 (>= 7.0), libssl1.1 (>= 1.1.0), libtirpc3 (>= 1.1.4)
```

All the gluster lib versions are specified after `-VUpstream-Version` is specified.

The result of running `dpkg-scanpackages` is also attached.

[Packages.txt](https://github.com/gluster/glusterfs-debian/files/3816783/Packages.txt)

**Comment by kalebskeithley** [comment]
Hi,

Am 06.11.2019 um 15:05 schrieb Kaleb Keithley:
>
>
> On Wed, Nov 6, 2019 at 8:50 AM Patrick Matthäi <pmatthaei@debian.org
> <mailto:pmatthaei@debian.org>> wrote:
>
>     Am 06.11.2019 um 14:31 schrieb Kaleb Keithley:
>     >
>     > The packaging bits are copied verbatim (or nearly so) from Patrick's
>     > Debian packaging bits. The official Debian dist packages must
>     have the
>     > same problem. I just checked and there don't seem to have been any
>     > changes that would address this. 
>     >
>     > Not being a Debian packaging expert I can't say whether using
>     > -VUpstream-Version is correct, or whether it would adversely affect
>     > the non-glusterfs dependencies, e.g. libibverbs, where a specific
>     > version isn't specified. I suppose I could do a build with it
>     and see
>     > what happens.
>     >
>     > Otherwise, in a vacuum I'd probably err on the side of caution (and
>     > simplicity?) and add explicit Depends: to glusterfs-common for the
>     > specific/explicit version of libglusterfs0, libgfapi0,
>     libchangelog0,
>     > libgfrpc0, and libgfxdr0,
>
>     If this is the case, then upstream missed SONAME bumps for the
>     libraries
>
>
> glusterfs (upstream, downstream, etc.) has never used SONAME for
> library versioning.
>  
>
>     which implies, that they are not compatible
>
>
> Indeed, and that has always been the case.
>
> I suppose someone could make the case that it's a problem, and I
> personally wouldn't disagree, but I rather doubt anything is going to
> change after 10+ years of this. (At least libgfapi uses versioned
> symbols to maintain compatibility across versions.) But that's not a
> problem with the packaging files.
>
> Do you want to express an opinion about the use of -VUpstream-Version
> or explicit Depends: in the glusterfs-common section of the rules file?

I have commited:

 override_dh_makeshlibs:
-       dh_makeshlibs --no-scripts
+       dh_makeshlibs --no-scripts -VUpstream-Version

SONAME bumps would be a better solution, but this should already solve
50% of all problems. I will upload it with the next new release.

-- 
/*
Mit freundlichem Gruß / With kind regards,
 Patrick Matthäi
 GNU/Linux Debian Developer

  Blog: http://www.linux-dev.org/
E-Mail: pmatthaei@debian.org
        patrick@linux-dev.org
*/

**Comment by kalebskeithley** [comment]
I've made the same changes to the gluster community packaging files.
