### ISSUE TITLE
Missing packages on Bionic and Disco

### ISSUE THREAD

**Issue by golyalpha** [gluster/glusterfs-debian#36]
So, I've just tried to install glusterfs-7 onto both my PC and my arm64 SBC, mainly for testing. 

I've found out, that in Disco's case (my PC), the `glusterfs` package is missing from the PPA, so the glusterfs package (at version 5) is being installed from ubuntu repositories. `libglusterfs0` is available at version 7 from the PPA, in this case.

In Bionic's case, both `glusterfs` and `libglusterfs0` are missing from the PPA, so even though `glusterfs-server` gets installed at version 7, the underlying glusterfs is at version 3.13.

Bionic `apt-cache madison` of `glusterfs-server`:
```
# apt-cache madison glusterfs-server
glusterfs-server | 7.1-ubuntu1~bionic1 | http://ppa.launchpad.net/gluster/glusterfs-7/ubuntu bionic/main arm64 Packages
glusterfs-server | 3.13.2-1ubuntu1 | http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe arm64 Packages
glusterfs-server | 3.13.2-1build1 | http://ports.ubuntu.com/ubuntu-ports bionic/universe arm64 Packages
 glusterfs | 3.13.2-1build1 | http://ports.ubuntu.com/ubuntu-ports bionic/universe Sources
 glusterfs | 3.13.2-1ubuntu1 | http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe Sources
```
Nothing shows up for `libglusterfs0`

Disco `apt-cache madison` of `glusterfs-server`:
```
$ apt-cache madison glusterfs-server
glusterfs-server | 7.1-ubuntu1~disco1 | http://ppa.launchpad.net/gluster/glusterfs-7/ubuntu disco/main amd64 Packages
glusterfs-server |      5.3-2 | http://cz.archive.ubuntu.com/ubuntu disco/universe amd64 Packages
 glusterfs |      5.3-2 | http://cz.archive.ubuntu.com/ubuntu disco/universe Sources
```
And for `libglusterfs0`:
```
$ apt-cache madison libglusterfs0
libglusterfs0 | 7.0-ubuntu1~disco1 | http://ppa.launchpad.net/gluster/glusterfs-7/ubuntu disco/main amd64 Packages
libglusterfs0 |      5.3-2 | http://cz.archive.ubuntu.com/ubuntu disco/universe amd64 Packages
 glusterfs |      5.3-2 | http://cz.archive.ubuntu.com/ubuntu disco/universe Sources
```

**Comment by kalebskeithley** [comment]
the 5.11 and 7.1 packages were built with obsolete packaging bits. Not sure why. Seems to have been a mistake.

I've respun them with the correct packaging bits. They are in the queue for building.

(The build system seems to be paused, probably taking advantage of the holiday for maintenance. Check back to see if they're built.)
