### ISSUE TITLE
Deb repo: wheezy cannot validate SSL cert for HTTPS connection

### ISSUE THREAD

**Issue by renepavlik** [gluster/glusterfs-debian#4]
The Let's encrypt CA cert which signs SSL cert for repo web page is not present in wheezy's `ca-certificates.crt` bundle.

Apt throws error:

```
Failed to fetch https://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.8/Debian/wheezy/apt/dists/wheezy/main/binary-amd64/Packages: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

Therefore glusterfs debs cannot be fetched at all (with SSL validation on).

**Comment by rlanore** [comment]
For other user you can workarround with
```
echo "Acquire::https::download.gluster.org::Verify-Peer "false";" >> /etc/apt/apt.conf
```

**Comment by pschultz** [comment]
The certificate chain served by download.gluster.org contains the leaf cert twice. This trips up some clients (such as apt) while others are fine (such as curl and openssl itself):

```
openssl s_client -connect download.gluster.org:443 -servername download.gluster.org -showcerts                                                                                                                                                                     
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = download.gluster.org
verify return:1
---
Certificate chain
 0 s:/CN=download.gluster.org
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
-----BEGIN CERTIFICATE-----
[snip]
fV4Bmj8yFws41S8xTv9TdHaPnVCO6yQ6GuC79GHQNdTsEhhWg16GHdB9newdE6ng
icezUzOh5TkJ/pJeiH0zaG/OmpJM8VwdDbU4Y6/Swh4=
-----END CERTIFICATE-----
 1 s:/CN=download.gluster.org
 1 s:/CN=download.gluster.org
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
-----BEGIN CERTIFICATE-----
[snip]
fV4Bmj8yFws41S8xTv9TdHaPnVCO6yQ6GuC79GHQNdTsEhhWg16GHdB9newdE6ng
icezUzOh5TkJ/pJeiH0zaG/OmpJM8VwdDbU4Y6/Swh4=
-----END CERTIFICATE-----
 2 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
-----BEGIN CERTIFICATE-----
[snip]
PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
-----END CERTIFICATE-----
[snip]
    Start Time: 1499784552
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```
Whoever is in charge of download.gluster.org has to fix that.

**Comment by mscherer** [comment]
That is the default certbot behavior, and I do not see anything to change that in the option. You say this trip some client, but besides apt, do you know another one ? (as I guess apt do not implement ssl verification by itself).

How does it break ?

**Comment by pschultz** [comment]
I don't know which library apt uses.

It breaks because the first certificate in the chain is not issued by the second certificate in the chain. The default LE client writes fullchain.pem and cert.pem. Looks like `cat cert.pem fullchain.pem` got deployed, but it should just be fullchain.pem.

**Comment by pschultz** [comment]
I guess you or someone else just fixed it? apt-get update works now.

**Comment by mscherer** [comment]
So, as we have a fix upstream and no one said it wasn't working anymore, closing it

**Comment by renepavlik** [comment]
Thank you, it works now.
