### ISSUE TITLE
Fetching gpg key timing out

### ISSUE THREAD

**Issue by Nordal** [gluster/glusterfs-debian#40]
Hi, I'm trying to add the glusterfs-7 apt repository, but fetching the gpg key is timing out:
klu@DC-HPC:~$ sudo add-apt-repository ppa:gluster/glusterfs-7
 GlusterFS 7
 More info: https://launchpad.net/~gluster/+archive/ubuntu/glusterfs-7
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Error: retrieving gpg key timed out.

I also tried adding the key manually like this:
klu@DC-HPC:~$ sudo apt-key adv --keyserver keyserver.ubuntu.com:80 --recv-keys 13E01B7B3FE869A9
Executing: /tmp/apt-key-gpghome.OZXYQKUC62/gpg.1.sh --keyserver keyserver.ubuntu.com:80 --recv-keys 13E01B7B3FE869A9
gpg: keyserver receive failed: No keyserver available

Maybe theres an issue.

**Comment by kalebskeithley** [comment]
access to files on the download server don't have anything to do with the packaging files in this repo.

You can send email to one of the gluster mailing lists (devel@gluster.org or gluster-users@gluster.org) or mention it in #gluster or #gluster-dev @FreeNode IRC when this happens.

**Comment by kalebskeithley** [comment]
We have no control over launchpad or the PPAs other than building that packages that are hosted there. If launchpad's keyserver is down I suggest taking it up with the launchpad admins.
