### ISSUE TITLE
Install conflict with /usr/lib/x86_64-linux-gnu/glusterfs/glfsheal

### ISSUE THREAD

**Issue by rudnypc** [gluster/glusterfs-debian#43]
apt install glusterfs-server
Lendo listas de pacotes... Pronto
Construindo árvore de dependências
Lendo informação de estado... Pronto
The following additional packages will be installed:
  glusterfs-client glusterfs-common
Os NOVOS pacotes a seguir serão instalados:
  glusterfs-client glusterfs-common glusterfs-server
0 pacotes atualizados, 3 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.
É preciso baixar 0 B/11,6 MB de arquivos.
Depois desta operação, 25,9 MB adicionais de espaço em disco serão usados.
Você quer continuar? [S/n] s
A seleccionar pacote anteriormente não seleccionado glusterfs-common.
(Lendo banco de dados ... 33076 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar .../glusterfs-common_8.1-1_amd64.deb ...
A descompactar glusterfs-common (8.1-1) ...
A seleccionar pacote anteriormente não seleccionado glusterfs-client.
A preparar para desempacotar .../glusterfs-client_8.1-1_amd64.deb ...
A descompactar glusterfs-client (8.1-1) ...
A seleccionar pacote anteriormente não seleccionado glusterfs-server.
A preparar para desempacotar .../glusterfs-server_8.1-1_amd64.deb ...
A descompactar glusterfs-server (8.1-1) ...
dpkg: erro ao processar o arquivo /var/cache/apt/archives/glusterfs-server_8.1-1_amd64.deb (--unpack):
 a tentar sobre-escrever '/usr/lib/x86_64-linux-gnu/glusterfs/glfsheal', que também está no pacote glusterfs-common 8.1-1
dpkg-deb: erro: o subprocesso colar foi morto pelo sinal (Pipe quebrado)
Erros foram encontrados durante o processamento de:
 /var/cache/apt/archives/glusterfs-server_8.1-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by kalebskeithley** [comment]
which debian or ubuntu distribution is this?

**Comment by rudnypc** [comment]
debian 9

**Comment by kalebskeithley** [comment]
fixed in glusterfs-8.1-2
