### ISSUE TITLE
8.2.x - mount-shared-storage.sh is missing

### ISSUE THREAD

**Issue by itzonban** [gluster/glusterfs-debian#44]
Hi,

in Version 8.2.x for Debian 10 Buster the file **mount-shared-storage.sh** is missing.

Running `systemctl start glusterfssharedstorage.service` fails with error message:

`glusterfssharedstorage.service: Failed at step EXEC spawning /usr/libexec/glusterfs/mount-shared-storage.sh: No such file or directory`

**Comment by kalebskeithley** [comment]
fixed in latest builds of 7.8 and 8.2 for buster and bullseye (not an issue on 7.8 for stretch)
Ubuntu builds in Launchpad coming soon.
