### ISSUE TITLE
Can you provide glusterfs-ganesha.deb since Debian/Ubuntu both provide requrements.

### ISSUE THREAD

**Issue by upst-io** [gluster/glusterfs-debian#45]
This Issue was suggested to be raised by @kalebskeithley after discussion in #gluster on freenode.

glusterfs with ganesha providing HA NFSv4 is not currently available for Debian/Ubuntu since there is no glusterfs-ganesha.deb to provide the ganesha HA integration.

Could this be added please ?

**Comment by Keeper-of-the-Keys** [comment]
Hey we also just ran into this, is this blocked by something specific?
Are there build instructions to build from source?

Thanks

**Comment by kalebskeithley** [comment]
New builds of 8.6 and 9.3 on bionic, focal, hirsute, and impish in launchpad; and buster, bullseye, and bookworm on download.gluster.org include glusterfs-ganesha.deb.

Going forward the next releases will include glusterfs-ganesha.deb too.

**Comment by Keeper-of-the-Keys** [comment]
Great thanks!
