### ISSUE TITLE
Ubuntu glusterfs-9 ppa lacking arm64 or other architecture

### ISSUE THREAD

**Issue by jasworks** [gluster/glusterfs-debian#47]
I am using glusterfs-8 ppa package and it has both amd64 and armv8 platform. Hence I can use it in both architecture (which is my current setup). 

Can't upgrade to glusterfs-9 due to lack of arm architecture. Can this be added back?

**Comment by kalebskeithley** [comment]
The presence or lack of packages is not a bug in these debian package files.

You can ask about packages in #gluster or #gluster-dev on IRC @freenode, one of the slack channels (e.g. #gluster athttps://app.slack.com/client/TH79R0GAC/CH9M2KF60 ) or the mailing lists (e.g. mailto:gluster-users@gluster.org)
