### ISSUE TITLE
Gluster 8-latest apt repo does not point to latest version 

### ISSUE THREAD

**Issue by IvanRossi** [gluster/glusterfs-debian#49]
Not sure it is the right place to signal this issue.

I noticed that Gluster 8 latest points to gluster 8.3 while there is a 8.4 repo as well.

See:

1.  https://download.gluster.org/pub/gluster/glusterfs/8/8.4/Debian/buster/amd64/apt/pool/main/g/glusterfs/
2.  https://download.gluster.org/pub/gluster/glusterfs/8/LATEST/Debian/buster/amd64/apt/pool/main/g/glusterfs/

**Comment by kalebskeithley** [comment]
Off hand, no, the LATEST symlink is not specific to Debian. There are usually Fedora, and sometimes CentOS/RHEL packages too. :-)

Also the symlink is often not updated until all the X.y (8.4 in this case) packages are there.

Looks like the symlink did get fixed though at some point. Closing.
