### ISSUE TITLE
glusterfs-server_3.11.3-1 for Jessie is missing init.d file

### ISSUE THREAD

**Issue by zstyblik** [gluster/glusterfs-debian#5]
Hello,

Debian package glusterfs-server_3.11.3-1 for Jessie is missing `/etc/init.d/glusterfs-server`, resp. init.d file. This file is present in glusterfs-server_3.11.2-1 and has always been present. I really cannot think of reason why this file should be missing, but it is.

Thanks.

**Comment by kalebskeithley** [comment]
Doesn't Jessie have systemd? My jessie box that I do package builds on seems to have it. Am I mistaken?

I realize that this is possibly painful but the point or goal is to get people to switch to the glusterd.service file instead of sysvinit. I.e. get people to switch before 3.12 is released.

And remember, 3.11 is a STM release. It's going to be EOL soon.

**Comment by zstyblik** [comment]
It does have systemd, but not even systemd service is present. Also, as I've said before glusterfs-server_3.11.2-1 had init.d file, glusterfs-server_3.11.3-1 doesn't. Why and how is missing, I don't know, but I doubt anyone would make a sudden switch from init.d file to systemd between patch versions.

I agree, 3.11 is STM and 3.11.3 was the last release(stated on the web/release notes due to 3.12), but that's no excuse for not fixing the package. Package is broken out of the box and doesn't work. I really don't think users should supply systemd unit or init.d file just for this package build just because package build got somehow broken.

**Comment by zstyblik** [comment]
If you download debpkg glusterfs-server_3.11.3-1 for Debian Jessie and examine its contents, you will see there is only `/etc/glusterfs` in `/etc`. If there was systemd unit(which isn't present even in repository), it would have been placed in `/lib/systemd/...`. Also, there would be `dh-systemd` in `Build-Depends` in `debian/control`.

**Comment by kalebskeithley** [comment]
glusterfs*_3.11.3-2 and glusterfs*_3.12.0 .debs on download.gluster.org have systemd .service files.  (and 3.11 is now EOL)

**Comment by zstyblik** [comment]
On behalf of Debian users, thank you :)

**Comment by richard-scott** [comment]
The 3.12.0 package still lacks systemd '.service'. files.

**Comment by kalebskeithley** [comment]
according to `dpkg-deb -c ... ` the 3.12.0-1 (jessie) and 3.12.0-2 (stretch) -server packages both have

drwxr-xr-x root/root         0 2017-09-01 08:16 ./lib/
drwxr-xr-x root/root         0 2017-09-01 08:16 ./lib/systemd/
drwxr-xr-x root/root         0 2017-09-01 08:16 ./lib/systemd/system/
-rw-r--r-- root/root       466 2017-09-01 08:16 ./lib/systemd/system/glusterd.service
-rw-r--r-- root/root       379 2017-09-01 08:16 ./lib/systemd/system/glustereventsd.service
-rw-r--r-- root/root       301 2017-09-01 08:16 ./lib/systemd/system/glusterfssharedstorage.service
