### ISSUE TITLE
Bad Libfuse dependency in Gluster 9 packages for Bionic.

### ISSUE THREAD

**Issue by nepella** [gluster/glusterfs-debian#50]
Commit 24a1988 changed the 9.x Bionic packages to depend on Libfuse3 instead of Libfuse, but [Bionic only has Libfuse2](<https://packages.ubuntu.com/search?keywords=libfuse&suite=bionic>), so the [build fails](<https://launchpadlibrarian.net/531234816/buildlog_ubuntu-bionic-amd64.glusterfs_9.1-ubuntu1~bionic2_BUILDING.txt.gz>). Could the commit be reverted?

**Comment by kalebskeithley** [comment]
fixed, launchpad is rebuilding glusterfs-9.1 for bionic

**Comment by nepella** [comment]
The build is still unhappy. I think you meant to type `--disable-linux-io_uring`, not `disable-linux-io_uring`, in 8565c82. (The changelog has it right.)

**Comment by nepella** [comment]
@kalebskeithley: I forgot to ping you above. (Apologies if you already saw it.)

**Comment by kalebskeithley** [comment]
Not a problem. I had actually seen the subsequent build failure and fixed it before I saw your comment here.

The armhfp build is still failing for other reasons, but the other four arches built.
