### ISSUE TITLE
PPA 7 last update published version 8.5

### ISSUE THREAD

**Issue by Nottt** [gluster/glusterfs-debian#51]
I was using glusterfs with version 7.9, and now I can't install this version on my servers.

The performance of the new version is not good. How can I download a older build meanwhile?

**Comment by kalebskeithley** [comment]
Launchpad has a "Contact this team's members" on the PPA page for reporting these sorts of things.

This issue tracker is for reporting issues with the packaging files in this repo.

But I have deleted the 8.5 build from the glusterfs-7 PPA.

**Comment by Nottt** [comment]
Hi is it possible to release the version 7.9 again for bionic ? Now there is no release for bionic
