### ISSUE TITLE
Ubuntu 22.04 PPA broken

### ISSUE THREAD

**Issue by fredbcode** [gluster/glusterfs-debian#56]
Hello

Missing dependency on Jammy, with PPA  

```
The following packages have unmet dependencies:
 glusterfs-server : Depends: liburing1 but it is not installable
```

liburing1 is not available as package

**Comment by fredbcode** [comment]
Just for testing, I tried without liburing1 and now I'm unable to mount the volume although gluster volume status
 status is good

**Comment by kalebskeithley** [comment]
new glusterfs-9 and glusterfs-10 packages are built for jammy with liburing2

Open a separate issue against gluster for the mount problem when built w/o liburing.
