### ISSUE TITLE
directories are missing permissions

### ISSUE THREAD

**Issue by sanjurakonde** [gluster/glusterfs-debian#57]
gluster related directories such as /var/lib/glusterd are having restricted permissions as 700 in Ubuntu, where as we have them as 755 in Fedora. This is causing multiple "permission denied" issues at glusterfs setup.

**Comment by kalebskeithley** [comment]
I installed glusterfs-10 from https://launchpad.net/~gluster/ on my focal machine and /var/lib/glusterd is 0755.

&gt; ls -ld /var/lib/glusterd/
drwxr-xr-x 14 root root 4096 Oct 29  2019 /var/lib/glusterd/

**Comment by kalebskeithley** [comment]
Am I missing something or can I close this PR?

**Comment by kalebskeithley** [comment]
Doesn't seem to be real, and apparently the reporter is no longer working on gluster.
