### ISSUE TITLE
Possible packaging conflict with Debian

### ISSUE THREAD

**Issue by alexrudd2** [gluster/glusterfs-debian#58]
Debian decided (in [#991383](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=991383)) to split out the `/usr/sbin/gluster` binary.  It was removed from `glusterfs-server` and installed in a new package `glusterfs-cli`.  

As far as I can tell they didn't attempt to upstream this packaging change.  IMO they also made a packaging mistake, see [#1023622](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023622).  This is fixable by manually installing `glusterfs-cli`

It's unclear to me what will happen if someone attempts to install the `glusterfs-cli` package with the PPA active.  I suspect there will be a conflict with two packages (PPA's `glusterfs-server` and Debian's `glusterfs-cli`) both attempting to provide the same file. 

Perhaps a `Conflicts-With:` is necessary?  
Perhaps this PPA would like to adopt Debian's packaging change?

**Comment by kalebskeithley** [comment]
Perhaps the Debian/Ubuntu packagers could _talk_ to us?  There was absolutely no reason for the Debian packages to seperate the gluster CLI into a separate package. It was done in RPM packages (Fedora, CentOS, RHGS) to support gdeploy in RHGS.  AFAIK debian/ubuntu doesn't have gdeploy and never needed this change.  I've added a dummy glusterfs-cli .deb in 11.0
