### ISSUE TITLE
glusterfs-server_3.12.0-1 for Stretch is missing init.d/systemd files

### ISSUE THREAD

**Issue by richard-scott** [gluster/glusterfs-debian#6]
When installing Gluster v3.12.0 on a new server it is missing any init.d/systemd files so you are unable to activate/start any Gluster services.

On a v3.11 install I had the following:
```
/etc/init.d/glusterfs-server
/lib/systemd/system/glusterd.service
/lib/systemd/system/glustereventsd.service
```

These are missing on the latest build from here:
https://download.gluster.org/pub/gluster/glusterfs/3.12/3.12.0/Debian/

**Comment by gutleib** [comment]
Is it a flop in a build?
I also have bumped into this.
Seeing only _very_ recent updates on it, is it a one time issue?

**Comment by kalebskeithley** [comment]
I respun the stretch 3.12.0 .debs.  I didn't change any of the packaging bits but this time the systemd .service files are in the .debs.  ???
glusterfs*_3.12.0-2 for stretch are on download.gluster.org now.

**Comment by richard-scott** [comment]
@kalebskeithley Thanks for fixing this :-)
