### ISSUE TITLE
Ubuntu 24.04 PPA broken

### ISSUE THREAD

**Issue by Caprico85** [gluster/glusterfs-debian#61]
Hello

`glusterfs-common` from https://launchpad.net/~gluster/+archive/ubuntu/glusterfs-11 cannot be installed on Ubuntu 24.04 (noble).

`glusterfs-common` depends on `libaio1`, but this package doesn't exist on 24.04 anymore. `libaio1t64` does exist though. So I guess this is related to Ubuntu's 64 bit timestamps transition.

See:
https://packages.ubuntu.com/noble/libaio1 (doesn't exist)
https://packages.ubuntu.com/noble/libaio1t64 (exists)

Regards

**Comment by patabid** [comment]
Second this, just went to install it in an Ubuntu 24.04 test machine and got the following: 

```
$ sudo apt install glusterfs-client
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 glusterfs-common : Depends: libaio1 (>= 0.3.93) but it is not installable
E: Unable to correct problems, you have held broken packages.

```

Installed libaiot64 manually 
`$ sudo apt install libaio1t64`

It is version 0.3.113 in the Ubuntu repos, but this had no affect at fixing the dependency error.

**Comment by patabid** [comment]
Quick follow up to this, I have built gluster 11.1 from source using libaio1t64 this morning and it appears to be able to mount the gluster volume as expected without issue. I am not trying the server side at all, just the client side but it appears to be functioning as expected.

**Comment by Caprico85** [comment]
Copied over to main repository: https://github.com/gluster/glusterfs/issues/4354

**Comment by Empor-co** [comment]
Still broken

**Comment by BitWise-0x** [comment]
> Quick follow up to this, I have built gluster 11.1 from source using libaio1t64 this morning and it appears to be able to mount the gluster volume as expected without issue. I am not trying the server side at all, just the client side but it appears to be functioning as expected.

same issue here, rebuilding didn't fix the issue.  any update on this?

**Comment by Caprico85** [comment]
Packages were finally updated. Thank you.
