### ISSUE TITLE
There is no /etc/sysconfig in Debian

### ISSUE THREAD

**Issue by zstyblik** [gluster/glusterfs-debian#7]
Hello,

it seems that glusterd.service references EnvironmentFile `/etc/sysconfig/glusterd`. However, there is no such directory in Debian, but there is `/etc/default`.

This is at least in 3.11.3 for Debian Jessie. I couldn't find which repository is the source of this file, therefore I'm unable to investigate further.

Impact is probably low(due to `EnvironmentFile-=`) as long as you're not planning to set environment variables.

Thanks

**Comment by kalebskeithley** [comment]
fixed in 3.12.0-3, jessie, stretch, buster
and ubuntu on launchpad
