### ISSUE TITLE
glusterd.service systemd unit requires rpcbind.service, not found/not needed

### ISSUE THREAD

**Issue by zstyblik** [gluster/glusterfs-debian#8]
Hello,

observed with 3.11.3 for Debian Jessie, `glusterd.service` systemd unit requires `rpcbind.service` in order to start. This is a hard requirement from systemd's point of view.

However, `rpcbind.service` would be installed via `nfs-common` which is only suggested dependency. Also, `rpcbind.service` is required only when you want to use NFS. You can happily use glusterfs alone without `rpcbind.service` and NFS. Despite I understand use-cases vary, I see this as sort of unneeded dependency.

Anyway, I understand it's hard to please everyone. Therefore, glusterfs-server should probably have hard dependency either on `nfs-common` or `rpcbind`(?).

Thanks.

**Comment by atinmu** [comment]
My understanding is this is not required as long as gluster-nfs service is not brought up and gluster-nfs has been already deprecated for the favour of nfs-ganesha. Does it make sense to take out this dependency, @nixpanic m Jiffin, Soumya?

**Comment by nixpanic** [comment]
Indeed, if Gluster/NFS (aka gNFS) is packaged, the dependency on rpcbind is correct. Currently Gluster/NFS is an optional component for building, but I think all distributions still do it. With Gluster 4.0 at least Fedora and CentOS packages will not contain Gluster/NFS anymore, and we recommend other distributions to drop it as well. At that point, the dependency on rpcbind can be removed from the glusterd.service too.

**Comment by kalebskeithley** [comment]
fixed in 3.12.0-3, jessie, stretch, buster
and ubuntu on launchpad

**Comment by zstyblik** [comment]
I presume 3.11.x packages will remain ... broken?

**Comment by thelordoftheboards** [comment]
3.11.2 fails for me on Ubuntu 17.10 in the same fashion.

**Comment by kalebskeithley** [comment]
3.11 was a STM release, it reached EOL in May 2017. Upgrade to 3.12 or later.

**Comment by thelordoftheboards** [comment]
@kalebskeithley Thank you very much. I followed your advise.
